[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.6", features = [] }
tauri-plugin-dialog = "2.7.3"
pm2-core = { path = "../wasm/pm2-core" }
mongo-core = { path = "../wasm/mongo-core" }
memmap2 = "0.9"
rayon = "1.12"
hashbrown = "0.17"
zlib-rs = { version = "0.6", default-features = false, features = [
  "rust-allocator",
  "__internal-api",
] }
libdeflater = "1.26.1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 16
panic = "abort"
strip = "symbols"
