#!/usr/bin/env node
/**
 * Rebuild pm2-core and mongo-core Wasm and embed bytes for the Vite app (no URL fetch).
 * Requires: rustc/cargo (wasm32-unknown-unknown), wasm-bindgen CLI matching Cargo.toml,
 * and wasm-opt (Binaryen) on PATH — install from https://github.com/WebAssembly/binaryen/releases
 */
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function run(cmd, cwd = root, extraEnv = {}) {
  console.log(`$ ${cmd}`);
  execSync(cmd, {
    cwd,
    stdio: "inherit",
    shell: true,
    env: { ...process.env, ...extraEnv },
  });
}

function requireWasmOpt() {
  try {
    const v = execSync("wasm-opt --version", { encoding: "utf8", shell: true }).trim();
    console.log(`wasm-opt: ${v}`);
  } catch {
    console.error(
      "wasm-opt not found. Install Binaryen and put wasm-opt on PATH:\n" +
        "  https://github.com/WebAssembly/binaryen/releases\n" +
        "  (Windows: extract bin/wasm-opt.exe into a directory on PATH)",
    );
    process.exit(1);
  }
}

function buildCrate({ crateDir, wasmName, pkgDir, bytesTs, exportConst }) {
  const cratePath = path.join(root, crateDir);
  const wasmOut = path.join(cratePath, "target", "wasm32-unknown-unknown", "release", `${wasmName}.wasm`);

  console.log(`\n=== Building ${wasmName} (${crateDir}) ===`);
  run(`cargo test --manifest-path "${crateDir}/Cargo.toml"`);
  run(`cargo build --manifest-path "${crateDir}/Cargo.toml" --target wasm32-unknown-unknown --release`);

  fs.mkdirSync(pkgDir, { recursive: true });
  run(`wasm-bindgen --target web --out-dir "${pkgDir}" --out-name ${wasmName} "${wasmOut}"`);

  const wasmBgPath = path.join(pkgDir, `${wasmName}_bg.wasm`);
  run(
    `wasm-opt -O3 --enable-simd --enable-relaxed-simd --enable-tail-call --enable-extended-const --enable-bulk-memory --enable-mutable-globals --enable-sign-ext -o "${wasmBgPath}" "${wasmBgPath}"`,
  );
  const wasmBytes = fs.readFileSync(wasmBgPath);
  console.log(`wasm-opt -O3 → ${wasmBytes.length} bytes`);

  fs.writeFileSync(
    bytesTs,
    `// Generated by npm run wasm:build — do not edit.\nexport const ${exportConst} =\n  ${JSON.stringify(wasmBytes.toString("base64"))};\n`,
  );
  console.log(`embedded ${wasmBytes.length} wasm bytes → ${path.relative(root, bytesTs)}`);

  const jsPath = path.join(pkgDir, `${wasmName}.js`);
  let js = fs.readFileSync(jsPath, "utf8");
  const urlDefault =
    /if\s*\(\s*(?:typeof\s+module_or_path\s*===\s*'undefined'|module_or_path\s*===\s*undefined)\s*\)\s*\{\s*module_or_path\s*=\s*new URL\(\s*'[a-zA-Z0-9_-]+_bg\.wasm'\s*,\s*import\.meta\.url\s*\)\s*;\s*\}/;
  if (!urlDefault.test(js)) {
    console.error(`failed to patch ${wasmName}.js URL default (pattern not found)`);
    process.exit(1);
  }
  js = js.replace(
    urlDefault,
    `if (module_or_path === undefined) {
        throw new Error('${wasmName}: pass WebAssembly.Module or bytes (embedded wasm)');
    }`,
  );
  fs.writeFileSync(jsPath, js);
  console.log(`patched ${wasmName}.js to avoid URL wasm fetch`);
}

requireWasmOpt();

// 1. PM2 Core
buildCrate({
  crateDir: "wasm/pm2-core",
  wasmName: "pm2_core",
  pkgDir: path.join(root, "src", "wasm", "pkg"),
  bytesTs: path.join(root, "src", "wasm", "pm2CoreBytes.ts"),
  exportConst: "PM2_CORE_WASM_BASE64",
});

// 2. Mongo Core
buildCrate({
  crateDir: "wasm/mongo-core",
  wasmName: "mongo_core",
  pkgDir: path.join(root, "src", "wasm", "pkg_mongo"),
  bytesTs: path.join(root, "src", "wasm", "mongoCoreBytes.ts"),
  exportConst: "MONGO_CORE_WASM_BASE64",
});
