#!/usr/bin/env node
/**
 * Rebuild pm2-core Wasm and embed bytes for the Vite app (no URL fetch).
 * Requires: rustc/cargo (wasm32-unknown-unknown), wasm-bindgen CLI matching Cargo.toml,
 * and wasm-opt (Binaryen) on PATH — install from https://github.com/WebAssembly/binaryen/releases
 */
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const crate = path.join(root, "wasm", "pm2-core");
const wasmOut = path.join(crate, "target", "wasm32-unknown-unknown", "release", "pm2_core.wasm");
const pkgDir = path.join(root, "src", "wasm", "pkg");
const bytesTs = path.join(root, "src", "wasm", "pm2CoreBytes.ts");

function run(cmd, cwd = root, extraEnv = {}) {
  console.log(`$ ${cmd}`);
  execSync(cmd, {
    cwd,
    stdio: "inherit",
    shell: true,
    env: { ...process.env, ...extraEnv },
  });
}

function requireWasmOpt() {
  try {
    const v = execSync("wasm-opt --version", { encoding: "utf8", shell: true }).trim();
    console.log(`wasm-opt: ${v}`);
  } catch {
    console.error(
      "wasm-opt not found. Install Binaryen and put wasm-opt on PATH:\n" +
        "  https://github.com/WebAssembly/binaryen/releases\n" +
        "  (Windows: extract bin/wasm-opt.exe into a directory on PATH)",
    );
    process.exit(1);
  }
}

requireWasmOpt();

run("cargo test --manifest-path wasm/pm2-core/Cargo.toml");
run(
  "cargo build --manifest-path wasm/pm2-core/Cargo.toml --target wasm32-unknown-unknown --release",
);

fs.mkdirSync(pkgDir, { recursive: true });
run(
  `wasm-bindgen --target web --out-dir "${pkgDir}" --out-name pm2_core "${wasmOut}"`,
);

const wasmPath = path.join(pkgDir, "pm2_core_bg.wasm");
run(
  `wasm-opt -O3 --enable-simd --enable-relaxed-simd --enable-tail-call --enable-extended-const --enable-bulk-memory --enable-mutable-globals --enable-sign-ext -o "${wasmPath}" "${wasmPath}"`,
);
const wasm = fs.readFileSync(wasmPath);
console.log(`wasm-opt -O3 → ${wasm.length} bytes`);

fs.writeFileSync(
  bytesTs,
  `// Generated by npm run wasm:build — do not edit.\nexport const PM2_CORE_WASM_BASE64 =\n  ${JSON.stringify(wasm.toString("base64"))};\n`,
);
console.log(`embedded ${wasm.length} wasm bytes → ${path.relative(root, bytesTs)}`);

const jsPath = path.join(pkgDir, "pm2_core.js");
let js = fs.readFileSync(jsPath, "utf8");
const urlDefault =
  /if\s*\(\s*(?:typeof\s+module_or_path\s*===\s*'undefined'|module_or_path\s*===\s*undefined)\s*\)\s*\{\s*module_or_path\s*=\s*new URL\(\s*'pm2_core_bg\.wasm'\s*,\s*import\.meta\.url\s*\)\s*;\s*\}/;
if (!urlDefault.test(js)) {
  console.error("failed to patch pm2_core.js URL default (pattern not found)");
  process.exit(1);
}
js = js.replace(
  urlDefault,
  `if (module_or_path === undefined) {
        throw new Error('pm2_core: pass WebAssembly.Module or bytes (embedded wasm)');
    }`,
);
fs.writeFileSync(jsPath, js);
console.log("patched pm2_core.js to avoid URL wasm fetch");
